[[module]]
module = "target/wasm32-wasi/debug/codewalk-wagi.wasm"
route = "/..."

# We also need to load `templates/` into the Wagi instance so that the
# template renderer can do its thing.
#
# With content, we mapped `content` to `/`. But with `templates/`,
# we have kept the name the same.
volumes = { "/" = "content/" , "templates/" = "templates/"}