[[module]]
module = "target/wasm32-wasi/debug/codewalk-wagi.wasm"

# The route entry controls how Wagi matches incoming URL paths to modules. Before,
# this was just `/`, which meant that it matched ONLY `http://localhost:3000/`.
# Adding the `/...` tells it to match `http://localhost:3000/` AND anything underneath
# that path. So, for example, `http://localhost:3000/about` will match this route now.
# So will `http://localhost:3000/icky/icky/icky/ptang/zoop/boing`. Doing that route will be
# left as an exercise for the reader.
route = "/..."

# Remember: This makes everything in `content/` accessible to us within our Wagi module.
# So we already have access to `about.md`.
volumes = { "/" = "content/" }