# This is our new fileserver module. Note that we need to add it first because
# if we don't the `/...` rule for the other module will match before the 
# '/images/...' rule gets evaluated.
#
# Note that we are mapping the `images/` directory as a volume for our Wagi instance.
# We intentionally map it to `/` because we don't want the URL to be
# /images/images/foo.gif, but just /images/foo.gif
[[module]]
module = "modules/fileserver.gr.wasm"
route = "/images/..."
volumes = { "/" = "images/"}

[[module]]
module = "target/wasm32-wasi/debug/codewalk-wagi.wasm"
route = "/..."
volumes = { "/" = "content/" , "templates/" = "templates/"}